"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Icon from "@/components/icon";
import Modal from "@/components/modal";
import PhotoImage from "@/components/photo-image";
import { copyShareLink, request } from "@/lib/client-api";
import type { Comment, GalleryData, Photo } from "@/lib/gallery";

export default function GalleryApp({ data, isAdmin, albumView = false }: { data: GalleryData; isAdmin: boolean; albumView?: boolean }) {
  const [active, setActive] = useState<Photo | null>(null);
  const [notice, setNotice] = useState("");
  const photos = useMemo(() => data.albums.flatMap(album => album.photos.map(photo => ({ ...photo, album }))), [data.albums]);
  const featured = photos[0];
  const share = async (path = location.pathname) => { try { await copyShareLink(path); setNotice("分享链接已复制"); } catch (error) { setNotice(error instanceof Error ? error.message : "暂时无法复制链接"); } };
  return <main>
    <header className="site-header"><Link href="/" className="brand">拾光<span>·</span></Link><nav><a href="#albums">相册集</a><a href="#photos">照片</a><a href="#about">关于</a></nav><div className="header-actions">{isAdmin ? <Link href="/admin" className="button button-ghost"><Icon name="grid" size={15}/>管理影像</Link> : <Link href="/login" className="login-link">管理员登录</Link>}</div></header>
    {data.demo && <div className="demo-banner"><Icon name="sun" size={16}/><span>正在浏览示例影像。配置 MySQL 和管理员账号后，即可创建自己的相册。</span><Link href="/login">前往配置</Link></div>}
    {!albumView && <section className="hero"><div className="hero-copy"><p className="page-kicker">个人影像档案 · 2026</p><h1>把日子里的<br/><em>光，慢慢收好。</em></h1><p>这里收藏路过的风景、平凡的日常，以及那些值得被时间温柔对待的瞬间。</p><a className="text-link" href="#albums">翻阅相册 <Icon name="arrow" size={16}/></a></div>{featured && <div className="hero-image-wrap"><PhotoImage src={featured.src} alt={featured.title} className="hero-image" priority/><div className="hero-image-caption"><span>{featured.title}</span><span>{featured.location || "拾光影像"}</span></div></div>}</section>}
    {albumView && <section className="album-title"><Link href="/" className="back-link">← 全部相册</Link><p className="page-kicker">相册集</p><h1>{data.albums[0]?.title}</h1><p>{data.albums[0]?.description}</p></section>}
    <section id="albums" className="albums-section"><div className="section-heading"><div><p className="page-kicker">影像合集</p><h2>{albumView ? "这一册的光" : "慢慢翻阅每一段故事"}</h2></div><span>{data.albums.length} 本相册</span></div>{data.albums.length === 0 ? <div className="empty-state"><Icon name="camera" size={34}/><h2>还没有公开相册</h2><p>{isAdmin ? "从管理空间创建第一本相册吧。" : "摄影师正在整理新的故事。"}</p>{isAdmin && <Link href="/admin" className="button button-primary">去创建相册</Link>}</div> : <div className="album-list">{data.albums.map(album => <article className="album-card" key={album.id}><Link href={`/albums/${album.id}`} className="album-cover"><PhotoImage src={album.photos[0]?.src || ""} alt={album.title} sizes="(max-width: 700px) 100vw, 33vw"/><span>{album.photos.length} 张照片</span></Link><div className="album-meta"><div><p className="album-date">{new Date(album.createdAt).toLocaleDateString("zh-CN", { year:"numeric", month:"long" })}</p><h3><Link href={`/albums/${album.id}`}>{album.title}</Link></h3><p>{album.description}</p></div><button className="round-button" aria-label={`分享 ${album.title}`} onClick={() => share(`/albums/${album.id}`)}><Icon name="share" size={17}/></button></div></article>)}</div>}</section>
    {!albumView && <section id="photos" className="photo-section"><div className="section-heading"><div><p className="page-kicker">片刻收藏</p><h2>最近的照片</h2></div><span>{photos.length} 个瞬间</span></div><div className="photo-wall">{photos.map(({ album, ...photo }, index) => <button key={photo.id} className={`photo-tile photo-tile-${index % 5}`} onClick={() => setActive(photo)}><PhotoImage src={photo.src} alt={photo.title} sizes="(max-width: 700px) 50vw, 33vw"/><span><b>{photo.title}</b><small>{album.title}</small></span></button>)}</div></section>}
    {albumView && <section id="photos" className="photo-section album-photos"><div className="photo-wall">{photos.map((item, index) => <button key={item.id} className={`photo-tile photo-tile-${index % 5}`} onClick={() => setActive(item)}><PhotoImage src={item.src} alt={item.title}/><span><b>{item.title}</b><small>{item.location}</small></span></button>)}</div></section>}
    <section id="about" className="about-section"><p className="page-kicker">关于拾光</p><div><h2>有些事情，<br/>只适合用相片记住。</h2><p>这是一个人的摄影档案。愿每一次停留，都能在这里找到一个安静的位置。</p><button onClick={() => share()} className="text-link">分享这座影像馆 <Icon name="share" size={16}/></button></div></section>
    <footer><span>拾光 · 个人影像档案</span><span>用心保存每一次看见</span></footer>{notice && <div className="toast" role="status">{notice}<button onClick={() => setNotice("")} aria-label="关闭">×</button></div>}{active && <PhotoDialog photo={active} demo={data.demo} onClose={() => setActive(null)} onShare={() => share(`/albums/${active.albumId}`)} />}
  </main>;
}

function PhotoDialog({ photo, demo, onClose, onShare }: { photo: Photo; demo: boolean; onClose: () => void; onShare: () => void }) {
  const [likes, setLikes] = useState(photo.likes); const [liked, setLiked] = useState(false); const [comments, setComments] = useState<Comment[]>([]); const [loading, setLoading] = useState(!demo); const [sending, setSending] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (demo) return; let alive = true; Promise.all([request<{likes:number;liked:boolean}>(`/api/photos/${photo.id}/like`), request<{comments:Comment[]}>(`/api/photos/${photo.id}/comments`)]).then(([like, note]) => { if (alive) { setLikes(like.likes); setLiked(like.liked); setComments(note.comments); } }).catch(() => { if (alive) setError("互动内容暂时无法加载。"); }).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [photo.id, demo]);
  const toggle = async () => { try { const result = await request<{likes:number;liked:boolean}>(`/api/photos/${photo.id}/like`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({liked:!liked}) }); setLikes(result.likes); setLiked(result.liked); } catch (cause) { setError(cause instanceof Error ? cause.message : "点赞未成功"); } };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSending(true); setError(""); try { const result = await request<{comment:Comment}>(`/api/photos/${photo.id}/comments`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({author:form.get("author"),body:form.get("body")}) }); setComments(items => [result.comment, ...items]); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : "留言未发送"); } finally { setSending(false); } };
  return <Modal title={photo.title} onClose={onClose} wide><div className="photo-dialog"><PhotoImage src={photo.src} alt={photo.title} className="dialog-image" priority/><div className="photo-dialog-info"><p className="page-kicker">{photo.location || "拾光影像"}</p><h2>{photo.title}</h2>{photo.description && <p className="photo-description">{photo.description}</p>}<div className="photo-actions"><button className={`reaction ${liked ? "is-liked" : ""}`} onClick={toggle} disabled={loading || demo}><Icon name="heart" size={18}/>{likes} 人喜欢</button><button className="reaction" onClick={onShare}><Icon name="share" size={17}/>分享</button></div><div className="comment-area"><h3>留言 <span>{comments.length}</span></h3>{demo ? <p className="notice">示例模式不保存点赞和留言。完成数据库配置后即可开启互动。</p> : <>{error && <p className="notice notice-error">{error}</p>}{loading ? <p className="muted">正在载入留言…</p> : <div className="comment-list">{comments.map(comment => <div className="comment" key={comment.id}><b>{comment.author}</b><p>{comment.body}</p></div>)}</div>}<form onSubmit={submit} className="comment-form"><input name="author" required maxLength={40} placeholder="你的昵称"/><textarea name="body" required maxLength={1000} rows={3} placeholder="写下一句想说的话…"/><button className="button button-primary" disabled={sending}>{sending ? "正在发送…" : "发表留言"}</button></form></>}</div></div></div></Modal>;
}
