-- Lumen schema v1 · MySQL 8.0+. Datetimes use UTC; UUIDs are generated by the app.
-- Run `pnpm db:init` against a new database. This file never drops existing data.
CREATE TABLE IF NOT EXISTS albums (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  title VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  visibility ENUM('PUBLIC', 'PRIVATE') NOT NULL DEFAULT 'PUBLIC',
  created_at DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP(3)),
  updated_at DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP(3)),
  PRIMARY KEY (id),
  KEY albums_visibility_created (visibility, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS photos (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  album_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  storage_key CHAR(41) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  title VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  location VARCHAR(120) NOT NULL DEFAULT '',
  width INT UNSIGNED NOT NULL,
  height INT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP(3)),
  PRIMARY KEY (id),
  UNIQUE KEY photos_storage_key_unique (storage_key),
  KEY photos_album_created (album_id, created_at),
  CONSTRAINT photos_album_fk FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS comments (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  photo_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  author_name VARCHAR(40) NOT NULL,
  body VARCHAR(1000) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP(3)),
  PRIMARY KEY (id),
  KEY comments_photo_created (photo_id, created_at),
  CONSTRAINT comments_photo_fk FOREIGN KEY (photo_id) REFERENCES photos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS photo_likes (
  photo_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  visitor_hash BINARY(32) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP(3)),
  PRIMARY KEY (photo_id, visitor_hash),
  CONSTRAINT photo_likes_photo_fk FOREIGN KEY (photo_id) REFERENCES photos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
